version: '3'
services:
    db:
        image: 'postgres:10-alpine'
        environment:
            - POSTGRES_DB=server
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - '3050:80'
        depends_on:
            - server
            - client
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app 
        ports:
            - "3000:3000"
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        restart: on-failure
        ports:
            - "8000:8000"
        volumes:
            - ./server/server:/server
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py makemigrations &&
                   python manage.py migrate && 
                   python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=server
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
            - DB_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - db
            - redis

    
    