version: '3'
services:
    db:
        image: 'postgres:10-alpine'
        environment:
            - POSTGRES_DB=server
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        image: 'edraobdu/yac-nginx'
        ports:
            - '3050:80'
        depends_on:
            - server
            - client
    client:
        stdin_open: true
        image: 'edraobdu/yac-client'
        ports: 
            - "3000:3000"
    server:
        image: 'edraobdu/yac-server'
        restart: always
        ports:
            - "8000:8000"
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   daphne -b 0.0.0.0 -p 8000 server.asgi:application"
        environment:
            - DB_HOST=db
            - DB_NAME=server
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
            - DB_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - db
            - redis

    
    