# Generated by Django 2.0.2 on 2020-05-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20200525_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='password',
            new_name='hora',
        ),
    ]
